### ISSUE TITLE
Objects only?

### ISSUE THREAD

**Issue by ohenepee** [AnandChowdhary/fraud#47]
Can it be used to cache buffers or arraybuffers?

**Comment by AnandChowdhary** [comment]
Hi, @ohenepee; thanks for opening this issue! In general, anything that can be `JSON.stringify()`'d can be stored in Fraud, since it can be stored in a file and in an in-memory cache. This includes strings, objects, and buffers.

Depending on what your buffers contain, they should work with Fraud:

```js
const buf = Buffer.from([0x1, 0x2, 0x3, 0x4, 0x5]);
const json = JSON.stringify(buf); // works
```

Could you perhaps give me an example of your cache/array buffer?

**Comment by ohenepee** [comment]
Thanks
